name = "cinexx-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# Uncomment kalau mau pakai Pages Functions
# pages_build_output_dir = "./public"

[vars]
# Jangan taruh API key di sini!
# Set via: wrangler secret put TMDB_API_KEY

[[routes]]
pattern = "stream.internetdnsofficial.workers.dev*"
zone_name = "workers.dev"
